version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile/nginx
    ports:
      - "50051:50051"

  auth:
    image: node:20-alpine
    volumes:
      - ./servers:/opt/auth
    working_dir: /opt/auth
    command: yarn run tsx src/auth.ts
    ports:
      - "3000:3000"
    # コンテナ終了時に /tmp/tsx-0/32.pipe が残ってしまい、次の起動時に EADDRINUSE が発生するのを回避
    tmpfs:
      - /tmp

  app:
    image: node:20-alpine
    volumes:
      - ./servers:/opt/app
    working_dir: /opt/app
    command: yarn run tsx src/app.ts
    ports:
      - "4000:4000"
    # コンテナ終了時に /tmp/tsx-0/32.pipe が残ってしまい、次の起動時に EADDRINUSE が発生するのを回避
    tmpfs:
      - /tmp
